import nltk
from nltk.tokenize import word_tokenize

print("AI Chatbot: Hello! Type 'bye' to exit.")

qa_pairs = {
"hello":"Hello! How can I help you?",
"hi":"Hi there!",
"how are you":"I am fine. Thank you!",
"what is your name":"I am an AI Chatbot created using NLP.",
"who created you":"I was created using Python and NLP.",
"what is ai":"AI stands for Artificial Intelligence.",
"what is python":"Python is a popular programming language.",
"what is nlp":"NLP means Natural Language Processing.",
"what can you do":"I can answer simple questions.",
"what is machine learning":"Machine learning is a branch of AI.",
"what is deep learning":"Deep learning is a type of machine learning.",
"what is chatbot":"A chatbot is a program that talks with users.",
"what is data science":"Data science analyzes data for insights.",
"what is programming":"Programming is writing instructions for computers.",
"what is computer":"A computer is an electronic device.",
"what is internet":"Internet is a global network.",
"what is software":"Software is a set of programs.",
"what is hardware":"Hardware is physical computer parts.",
"what is cloud computing":"Cloud computing stores data online.",
"what is database":"Database stores organized data.",
"what is sql":"SQL is used to manage databases.",
"what is html":"HTML is used to create web pages.",
"what is css":"CSS styles web pages.",
"what is javascript":"JavaScript makes websites interactive.",
"what is github":"GitHub is used for code sharing.",
"what is vs code":"VS Code is a code editor.",
"what is operating system":"It manages computer hardware and software.",
"what is linux":"Linux is an open-source operating system.",
"what is windows":"Windows is a Microsoft operating system.",
"what is android":"Android is a mobile operating system.",
"what is ios":"iOS is Apple's mobile operating system.",
"what is network":"Network connects computers together.",
"what is wifi":"WiFi is wireless internet.",
"what is cybersecurity":"Cybersecurity protects computer systems.",
"what is hacking":"Hacking means unauthorized access.",
"what is encryption":"Encryption protects data.",
"what is algorithm":"Algorithm is a step-by-step solution.",
"what is api":"API allows software communication.",
"what is debugging":"Debugging fixes program errors.",
"what is compiler":"Compiler converts code to machine language.",
"what is interpreter":"Interpreter runs code line by line.",
"what is framework":"Framework helps build applications.",
"what is django":"Django is a Python web framework.",
"what is flask":"Flask is a lightweight Python framework.",
"what is tensorflow":"TensorFlow is used for AI models.",
"what is pytorch":"PyTorch is a deep learning library.",
"what is numpy":"NumPy handles numerical operations.",
"what is pandas":"Pandas is used for data analysis.",
"what is matplotlib":"Matplotlib is used for graphs.",
"what is seaborn":"Seaborn creates statistical charts.",
"what is opencv":"OpenCV processes images.",
"what is cnn":"CNN is used for image recognition.",
"what is rnn":"RNN is used for sequence data.",
"what is dataset":"Dataset is a collection of data.",
"what is training data":"Training data trains AI models.",
"what is testing data":"Testing data evaluates models.",
"what is overfitting":"Overfitting means model learns too much.",
"what is underfitting":"Underfitting means model learns too little.",
"what is big data":"Big data means large data sets.",
"what is analytics":"Analytics analyzes data.",
"what is visualization":"Visualization shows data graphically.",
"what is blockchain":"Blockchain stores secure transactions.",
"what is cryptocurrency":"Cryptocurrency is digital money.",
"what is bitcoin":"Bitcoin is a cryptocurrency.",
"what is ethereum":"Ethereum is a blockchain platform.",
"what is cloud":"Cloud stores data online.",
"what is google":"Google is a search engine.",
"what is youtube":"YouTube is a video platform.",
"what is facebook":"Facebook is a social media platform.",
"what is instagram":"Instagram is a photo sharing app.",
"what is twitter":"Twitter is a social network.",
"what is linkedin":"LinkedIn is a professional network.",
"what is email":"Email sends digital messages.",
"what is spam":"Spam is unwanted email.",
"what is firewall":"Firewall protects networks.",
"what is vpn":"VPN hides internet activity.",
"what is router":"Router connects networks.",
"what is modem":"Modem connects internet.",
"what is ram":"RAM is temporary memory.",
"what is rom":"ROM is permanent memory.",
"what is cpu":"CPU is the brain of computer.",
"what is gpu":"GPU processes graphics.",
"what is monitor":"Monitor displays output.",
"what is keyboard":"Keyboard inputs text.",
"what is mouse":"Mouse controls pointer.",
"what is printer":"Printer prints documents.",
"what is scanner":"Scanner digitizes documents.",
"what is usb":"USB connects devices.",
"what is bluetooth":"Bluetooth connects devices wirelessly.",
"what is file":"File stores information.",
"what is folder":"Folder organizes files.",
"what is backup":"Backup saves copies of data.",
"what is update":"Update improves software.",
"what is bug":"Bug is a program error."
}

while True:
    user_input = input("You: ").lower()

    if user_input == "bye":
        print("Bot: Goodbye! Have a nice day.")
        break

    elif user_input in qa_pairs:
        print("Bot:", qa_pairs[user_input])

    else:
        print("Bot: Sorry, I don't understand that.")